services:
  rabbitmq:
    image: rabbitmq:3.13.1-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: supersecret
    volumes:
      - ./advanced.config:/etc/rabbitmq/advanced.config:ro
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5


  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    env_file:
      - ./auth/.env
    environment:
      PORT: "3001"
      NODE_ENV: production
    ports:
      - "3001:3001"
    volumes:
      - ./secrets:/app/secrets:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 10s

  web:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_AUTH_URL: http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - auth
    restart: unless-stopped

  # menu-cms:
  #   image: node:18-alpine
  #   working_dir: /app
  #   command: sh -c "npm install && npm run dev"
  #   ports:
  #     - "3002:3002"
  #   environment:
  #     NEXT_PUBLIC_AUTH_URL: http://localhost:3001
  #   volumes:
  #     - ./menu-cms:/app
  #     - /app/node_modules
  #   depends_on:
  #     - auth
  #   restart: unless-stopped
    
  kitchen:
    build:
      context: ./kitchen
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://kitchen_user:kitchen_pass@postgres_kitchen:5432/kitchen?sslmode=disable
      RABBITMQ_URL: amqp://admin:supersecret@rabbitmq:5672/
      JWT_PUBLIC_KEY_PATH: /secrets/public.pem
      KITCHEN_PORT: "5000"
    volumes:
      - ./secrets:/secrets:ro
    depends_on:
      postgres_kitchen:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "5003:5000"

  delivery:
    build:
      context: ./delivery
      dockerfile: Dockerfile
    container_name: delivery_service
    depends_on:
      postgres_delivery:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./delivery/.env
    environment:
      TZ: UTC
      PORT: 3333
      HOST: 0.0.0.0
      LOG_LEVEL: info
      NODE_ENV: development
      
      DB_CONNECTION: pg
      DB_HOST: postgres_delivery
      DB_PORT: 5432
      DB_USER: delivery_user
      DB_PASSWORD: delivery_pass
      DB_DATABASE: delivery
      
      AUTH_SERVICE_URL: http://auth:3001
    ports:
      - '3333:3333'
    volumes:
      - ./delivery:/app
      - /app/node_modules
    command: ["node", "ace", "serve", "--watch"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  postgres_kitchen:
    image: postgres:16
    container_name: postgres_kitchen
    restart: always
    environment:
      POSTGRES_DB: kitchen
      POSTGRES_USER: kitchen_user
      POSTGRES_PASSWORD: kitchen_pass
    volumes:
      - pg_kitchen_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kitchen_user", "-d", "kitchen"]
      interval: 5s
      timeout: 2s
      retries: 5

  postgres_delivery:
    image: postgres:16
    container_name: postgres_delivery
    restart: always
    environment:
      POSTGRES_DB: delivery
      POSTGRES_USER: delivery_user
      POSTGRES_PASSWORD: delivery_pass
    volumes:
      - pg_delivery_data:/var/lib/postgresql/data
      - ./delivery/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5435:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "delivery_user", "-d", "delivery"]
      interval: 5s
      timeout: 2s
      retries: 5

volumes:
  pg_kitchen_data:
  pg_delivery_data:
  rabbitmq_data: