version: '3.9'

services:
  service-clients:
    build: ./client-service
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on: []

  service-commandes:
    build: ./command-service
    ports:
      - "8081:8081"
    environment:
      - DB_URL=${DB_URL}
    depends_on: []

  service-cuisine:
    build: ./kitchen-service
    ports:
      - "8082:8082"
    environment:
      - DB_URL=${DB_URL}
    depends_on: []
